# Generated by Django 5.2.11 on 2026-06-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('provider', 'ارائه\u200cدهنده'), ('admin', 'مدیر')], default='customer', help_text='User role in the system', max_length=10),
        ),
    ]
