# Generated by Django 5.2.11 on 2026-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled by customer'), ('rejected', 'Rejected by provider'), ('completed', 'Completed')], db_index=True, default='pending', max_length=10),
        ),
    ]
